/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ action }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/archer.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.03} position={[0, -2.5, 0]} >
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Erika_Archer_Body_Mesh" geometry={nodes.Erika_Archer_Body_Mesh.geometry} material={materials['Akai_MAT.001']} skeleton={nodes.Erika_Archer_Body_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Clothes_Mesh" geometry={nodes.Erika_Archer_Clothes_Mesh.geometry} material={materials['eyelash_MAT.001']} skeleton={nodes.Erika_Archer_Clothes_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Eyelashes_Mesh" geometry={nodes.Erika_Archer_Eyelashes_Mesh.geometry} material={materials['Body_MAT.001']} skeleton={nodes.Erika_Archer_Eyelashes_Mesh.skeleton} />
          <skinnedMesh name="Erika_Archer_Eyes_Mesh" geometry={nodes.Erika_Archer_Eyes_Mesh.geometry} material={materials['EyeSpec_MAT.001']} skeleton={nodes.Erika_Archer_Eyes_Mesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Archer.glb');

function usePrevious(value) {

  const ref = useRef();

  useEffect(() => {
    ref.current = value;
  }, [value]);

  return ref.current
}
